export class CarDetails {
  constructor(
    public carName?: string,
    public className?: string,
    public carType?: string,
    public price?: number,
    public isSuccess?: boolean,

    //Safety
    public electricHandbrake?: boolean,
    public powerAssistedSteering?: string,
    public activeParkAssist?: boolean,
    public tractionControl?: boolean,
    public tirePressureMonitoring?: boolean,
    public antiLockBrakingSystem?: boolean,
    public electroncStabilityControl?: boolean,
    public airbags?: number,
    public hillAssist?: boolean,
    public speedLimiter?: boolean,
    public autoStartStopFunctions?: boolean,
    public immobilizer?: boolean,
    public childSeats?: boolean,
    public electronicBrakeForceDistribution?: boolean,
    public cruiseControl?: boolean,

    //Performance
    public cylinders?: number,
    public maxToruqe: string = '',
    public fuelConsumption?: number,
    public fuelType?: number,
    public maxPower: string = '',
    public acceleration?: number,
    public maxSpeed?: number,
    public fuelTankCapacity?: number,
    public gearShifts?: number,

    //Interior
    public multiFunction?: boolean,
    public paddleShifters?: boolean,
    public leatherSteeringWheel?: boolean,
    public variableHeatedDriverPassengerSeat?: boolean,
    public powerTailgate?: boolean,
    public ambientLighting?: string,
    public numberOfSeats?: number,
    public keylessStartStop?: boolean,
    public rearParkingSensors?: boolean,
    public rearViewCamera?: boolean,
    public passengerSeat?: string,
    public centerLock?: boolean,
    public dashboard?: string,
    public driveModeSelect?: number,
    public acBackSeats?: boolean,
    public leatherTransmission?: boolean,
    public backHolder?: boolean,
    public keylessEntry?: boolean,
    public autoDimmingMirror?: boolean,
    public ac?: string,
    public autoFoldingBackSeats?: boolean,
    public frontParkingSensors?: boolean,
    public frontCamera?: boolean,
    public driverSeat?: string,
    public leatherSeats?: boolean,
    public electronicWindow?: boolean,

    //Exterior
    public rainSensor?: boolean,
    public fogLambs?: boolean,
    public rearLambs?: string,
    public autoLighting?: boolean,
    public wheelsWithTireSize?: string,
    public panoramaRoof?: boolean,
    public autoFoldingMirror?: boolean,
    public privacyGlass?: boolean,
    public headlamps?: string,
    public ledDaytimeRunningLamps?: boolean,
    public lightSensors?: boolean,
    public sunRoof?: boolean,
    public powerMirrors?: boolean,
    public trimSize?: string,

    //Multimedia
    public aux?: boolean,
    public usb?: boolean,
    public multifunctionSteeringWheel?: boolean,
    public touchscreen?: number,
    public wirlessCharger?: boolean,
    public bluetooth?: boolean,
    public headUpDisplay?: boolean,
    public smartphoneLinkSystem?: string,
    public navigationSystem?: boolean,
    public speakers?: boolean,
    public cdPlayer?: boolean,

    //Dimension
    public luggageBoxCapacity?: number,
    public clearance?: number,
    public width?: number,
    public wheelbase?: number,
    public length?: number,
    public height?: number
  ) {}
}
