export class CarDetails {
  constructor(
    public carName: string = "car name",
    public ClassName: string = "class name",
    public CarType: string = "AAA",
    public Price: number = 1000,

    //Safety 
    public ElectricHandbrake?: boolean,
    public PowerAssistedSteering: string = '',
    public ActiveParkAssist?: boolean,
    public TractionControl?: boolean,
    public TirePressureMonitoring?: boolean,
    public AntiLockBrakingSystem?: boolean,
    public ElectroncStabilityControl?: boolean,
    public Airbags?: number,
    public HillAssist?: boolean,
    public SpeedLimiter?: boolean,
    public AutoStartStopFunctions?: boolean,
    public Immobilizer?: boolean,
    public ChildSeats?: boolean,
    public ElectronicBrakeForceDistribution?: boolean,
    public CruiseControl?: boolean,

    //Performance
    public Cylinders?: number,
    public MaxToruqe: string = '',
    public FuelConsumption?: number,
    public FuelType?: number,
    public MaxPower: string = '',
    public Acceleration?: number,
    public MaxSpeed?: number,
    public FuelTankCapacity?: number,
    public GearShifts?: number,

    //Interior
    public MultiFunction?: boolean,
    public PaddleShifters?: boolean,
    public LeatherSteeringWheel?: boolean,
    public VariableHeatedDriverPassengerSeat?: boolean,
    public PowerTailgate?: boolean,
    public AmbientLighting: string = '',
    public NumberOfSeats?: number,
    public KeylessStartStop?: boolean,
    public RearParkingSensors?: boolean,
    public RearViewCamera?: boolean,
    public PassengerSeat: string = '',
    public CenterLock?: boolean,
    public Dashboard: string = '',
    public DriveModeSelect?: number,
    public AcBackSeats?: boolean,
    public LeatherTransmission?: boolean,
    public BackHolder?: boolean,
    public KeylessEntry?: boolean,
    public AutoDimmingMirror?: boolean,
    public Ac: string = '',
    public AutoFoldingBackSeats?: boolean,
    public FrontParkingSensors?: boolean,
    public FrontCamera?: boolean,
    public DriverSeat: string = '',
    public LeatherSeats?: boolean,
    public ElectronicWindow?: boolean,

    //Exterior
    public RainSensor?: boolean,
    public FogLambs?: boolean,
    public RearLambs: string = '',
    public AutoLighting?: boolean,
    public WheelsWithTireSize: string = '',
    public PanoramaRoof?: boolean,
    public AutoFoldingMirror?: boolean,
    public PrivacyGlass?: boolean,
    public Headlamps: string = '',
    public LedDaytimeRunningLamps?: boolean,
    public LightSensors?: boolean,
    public SunRoof?: boolean,
    public PowerMirrors?: boolean,
    public TrimSize: string = '',

    //Multimedia
    public Aux?: boolean,
    public Usb?: boolean,
    public MultifunctionSteeringWheel?: boolean,
    public Touchscreen?: number,
    public WirlessCharger?: boolean,
    public Bluetooth?: boolean,
    public HeadUpDisplay?: boolean,
    public SmartphoneLinkSystem: string = '',
    public NavigationSystem?: boolean,
    public Speakers?: boolean,
    public CdPlayer?: boolean,

    //Dimension
    public LuggageBoxCapacity?: number,
    public Clearance?: number,
    public Width?: number,
    public Wheelbase?: number,
    public Length?: number,
    public Height?: number
  ) {}
}
